# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlantedView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SlantedView
  pod 'SBASlantedView', :git => 'https://github.com/shoaib-akhtar/SlantedView.git'

  target 'SlantedViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SlantedViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
